version: 2

project_name: litebox

before:
  hooks:
    - go mod tidy
    - go run github.com/a-h/templ/cmd/templ@v0.3.1020 generate

builds:
  - id: litebox
    main: ./cmd/mailbox
    binary: litebox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.Date}}

archives:
  - id: binaries
    ids: [litebox]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - NOTICE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request

release:
  prerelease: auto
  mode: replace
  draft: true
  replace_existing_draft: true
  extra_files:
    - glob: ./release/*.tar.gz
    - glob: ./release/*.sha256
    - glob: ./release/setup.sh
