# syntax=docker/dockerfile:1.12
FROM golang:1.27.0-alpine3.23@sha256:3747dcba41c8b0db3211fda4db61638b980e17ac5bb3c94460a975a9cfe19395

ARG TEMPL_VERSION=v0.3.1020
ARG STATICCHECK_VERSION=v0.7.0
ARG GOVULNCHECK_VERSION=v1.6.0
ARG ACTIONLINT_VERSION=v1.7.12
ARG GOLANGCI_LINT_VERSION=v2.12.2

RUN apk add --no-cache bash build-base ca-certificates curl docker-cli docker-cli-compose git make

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go install github.com/a-h/templ/cmd/templ@${TEMPL_VERSION} \
    && go install honnef.co/go/tools/cmd/staticcheck@${STATICCHECK_VERSION} \
    && go install golang.org/x/vuln/cmd/govulncheck@${GOVULNCHECK_VERSION} \
    && go install github.com/rhysd/actionlint/cmd/actionlint@${ACTIONLINT_VERSION} \
    && go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}

WORKDIR /workspace
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .

ENV APP_ENV=development \
    APP_BASE_URL=http://localhost:8080 \
    APP_LISTEN_ADDR=:8080

EXPOSE 8080
CMD ["go", "run", "./cmd/mailbox", "serve"]
